### ISSUE TITLE
done and next buttons are under navigation bar

### ISSUE THREAD

**Issue by nutpantz** [newhinton/Timed-Silence#2]
Hard to use
![Screenshot_20240416-091810](https://github.com/newhinton/Timed-Silence/assets/12160507/57d2b90f-7f0a-40f9-89fb-e3bdd1fb380c)
![Screenshot_20240413-202433](https://github.com/newhinton/Timed-Silence/assets/12160507/59992a0c-f303-43b1-98e0-df2d8bdbfa45)

**Comment by newhinton** [comment]
Yes, this is the same issue as the other one you opened. The intros are copies of themselfes. It is already fixed, but not released.

The most easy way someone else suggested was to rotate the device, wich makes the done button accessible. Though, from the other tickets you created i gather you already found a workaround ;) 

Thanks for reporting!

Closing because 1b5abb3bac78c40ff653c8706f676b725f123885
