### ISSUE TITLE
feature req: alternate calendar support

### ISSUE THREAD

**Issue by nutpantz** [newhinton/Timed-Silence#5]
I don't use the Google calender app. I user essential pim for Android. None of my calenders info shows up in this app. my calender info shows up in other apps. ( Ie a third party agenda widget). Not sure how it works

I don't want my calender info synced with Google.

Maybe have a custom calenders event option so i can make appointment's in this app that i want to be silent without having to use Google calenders

**Comment by newhinton** [comment]
I only make use of android's internal calendar api, which exposes "external" calendars like davx5 or similar.

I have no first hand experience with essentialpim, but from what i could get in this forum, it will not be possible with "just" the e-pim app.

https://www.essentialpim.com/forum/viewtopic.php?t=38625

I dont have the time to maintain or develop a second source of calendars. Therefore i am going to close this issue, because i can't spend time on this.

I would suggest looking into syncing epim with a different [provider](https://www.essentialpim.com/help/index.html?adding_synchronization_account.htm), like nextcloud or similar. Then you can use https://f-droid.org/packages/at.bitfire.davdroid/ or similar to sync your calendar to the android system calendars. That would be the standard way to do it. Sorry i cant help you.
