### ISSUE TITLE
Crash when navigating to a calendar event day

### ISSUE THREAD

**Issue by nizarus** [newhinton/Timed-Silence#8]
I successfully selected a calendar (see #7). When I return to the main window and navigate to a day containing an event from that calendar the application crashes. 
With my calendar application I add an event to the selected calendar (today date) and the application crashes on start.

**Comment by newhinton** [comment]
Can you capture android-logs by any chance? I can help you out if you need help.

**Comment by nizarus** [comment]
How to do that ?

**Comment by newhinton** [comment]
You need to install the "android debug bridge (adb)". You can either use the [standalone tools](https://developer.android.com/tools/releases/platform-tools) if you are comfortable using the command line, or directly by installing [android studio](https://developer.android.com/studio). I really do recommend to use android studio, it provides a gui to actually access the logs.

After installing you need to enable [usb-debugging on your device (possibly also enable developer tools first)](https://developer.android.com/studio/debug/dev-options), and after connecting it to the pc with android studio, you can start the app so that it crashes, and then you should be able to copy the log.

Feel free to ask questions when you are getting stuck at some point, i am glad to help.

**Comment by nizarus** [comment]
I used adb before to install custom ROM on my old smartphones. Never used to debug applications. I will try and come back to you.

**Comment by nizarus** [comment]
I'm connected to my device with adb, but can't figure how to launch the application and get the log.

**Comment by newhinton** [comment]
You can use the following:

`adb -s "deviceid" logcat | grep time`

the `-s "deviceid" ` is only required if you have more than one device attached.

`| grep time` is optional, but it makes finding the appropriate logs more easy

The minimal example would be:

`adb logcat`

which should immediately start showing your device's logs if you have debug mode enabled.
Then you can start the app and the crash-log should just show up.

**Comment by nizarus** [comment]
Log file attached
[logTimedSilence.txt](https://github.com/newhinton/Timed-Silence/files/15065286/logTimedSilence.txt)

**Comment by newhinton** [comment]
Is it only an specific calendar? Or all of them?

**Comment by newhinton** [comment]
Did you use grep on the log?

**Comment by nizarus** [comment]
1 - I only tested with calendar. The application don't crash when the calendar is not added.
2 - Yep.

**Comment by newhinton** [comment]
Can you check if this also occurs with other calendars?

Could you get a log without grep? I think it cut out some stuff.

Thanks!

**Comment by nizarus** [comment]
Tested with one other calendar and it crashes.
Full log : https://pastebin.com/Dn1RcaR0

**Comment by newhinton** [comment]
Can you test this build:

[TimedSilence-release-v3.1.2-debug.zip](https://github.com/newhinton/Timed-Silence/files/15080267/TimedSilence-release-v3.1.2-debug.zip)


This should at least capture the exception itself, and log which calendar event breaks this. It's a bit hard to debug because i obviously dont have access to your device, but this will let us get a bit closer. 

The build is signed as the release, so you can just install it as an update, but i have not published it's sources.

**Comment by notIkibo** [comment]
![logcat.txt](https://github.com/newhinton/Timed-Silence/files/15084146/logcat.txt)

1. Samsung Galaxy S22, Android 14
2. It was the only rule
3. Now that it's Wednesday (for me), I can't open the app completely. It instantly crashes
4. Will test the APK, but not now
5. What a weird bug indeed

**Comment by nizarus** [comment]
@newhinton : No more crashes with 3.1.2.
But, the DND status is well activated at the beginning of the event, and remain active after its end.

**Comment by newhinton** [comment]
@nizarus This is expected. You should now have more logging output, especially with the `StateGenerator`.

It should look something like this:
`VolumeState(startTime=x, endTime=y, duration=z, state=a, reason=b, reasonDescription=c)`

Could you post that? Please check that reasonDescription does not contain sensitive private information!

Thank you for your patience!

**Comment by newhinton** [comment]
@nizarus I have an idea what might cause this. Can you confirm that the event that is problematic starts at the selected day, but ends on the next one?

**Comment by notIkibo** [comment]
It does fix it

**Comment by nizarus** [comment]
Sorry for the late reply.
1- In the log file, I have some lines with "StateGenerator" but nothing like "VolumeState(...)"
2- No, the event starts and ends in the same day.
